# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x0b\x61i.platform\" \n\x10InferenceRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"<\n\x11InferenceResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x02 \x01(\x02\x32\\\n\x10InferenceService\x12H\n\x07Predict\x12\x1d.ai.platform.InferenceRequest\x1a\x1e.ai.platform.InferenceResponseB(\n\x14\x63om.platform.ai.grpcB\x0eInferenceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.platform.ai.grpcB\016InferenceProtoP\001'
  _globals['_INFERENCEREQUEST']._serialized_start=32
  _globals['_INFERENCEREQUEST']._serialized_end=64
  _globals['_INFERENCERESPONSE']._serialized_start=66
  _globals['_INFERENCERESPONSE']._serialized_end=126
  _globals['_INFERENCESERVICE']._serialized_start=128
  _globals['_INFERENCESERVICE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
